### ISSUE TITLE
welche PHP Versionen empfohlen ?

### ISSUE THREAD

**Issue by agony09** [braeutigamj/villages-online#1]
Hallo guten Tag,
welche PHP Version wird hierfür empfohlen ?

**Comment by braeutigamj** [comment]
Bei http://demo.villages-online.de/ läuft es unter Version 5.6.

**Comment by agony09** [comment]
ok danke, wäre PHP 7.X auch möglich ?

**Comment by braeutigamj** [comment]
Ich habe demo.villages-online.de auf 7.2 umgestellt und es scheint auch jetzt noch zu funktionieren.

**Comment by agony09** [comment]
danke für die Info. Ist dieses Projekt weiter in Arbeit oder Entwicklung ?
Oder bleibt es so wie es momentan ist ?

**Comment by braeutigamj** [comment]
Es ist aktuell nicht in Entwicklung. Du kannst aber gerne jederzeit Änderungen pushen.

**Comment by agony09** [comment]
Ok, kann es sein das es eine Abwandlung von Farmers Game oder WaroftheIslands ist ?

**Comment by braeutigamj** [comment]
Eher von die-staemme.de

**Comment by agony09** [comment]
ich meinte das Script selbst. Das ist von Farmers Game oder War of Islands. Umgeändert

**Comment by braeutigamj** [comment]
Nein das ist selbstgeschrieben?

**Comment by agony09** [comment]
Siehe hier: http://barndays.yadia.de/
Das sind nahezu die identischen Scrips im Kern.

**Comment by braeutigamj** [comment]
Es tut mir Leid. Ich kenne den dortigen Quellcode nicht.
